language: python
python:
        - "3.5" 
#comment :-)
install:
        - pip install coverage
        - pip install colorama

script:
        - python test_rpn.py
        - coverage run test_rpn.py
        - coverage report
